spring.application.name=patient-service
server.port=4000
logging.level.root=info

# ===== Local PostgreSQL =====
spring.datasource.url=jdbc:postgresql://localhost:5432/patient_db
spring.datasource.username=postgres
spring.datasource.password=Elondada$1
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# ===== Kafka (local broker) =====
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

# ===== gRPC billing DISABLED =====
# Billing gRPC is turned off for local run. See BillingServiceGrpcClient.java
billing.grpc.enabled=false
